apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-cluster
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: single-replica-placement 
        requeueAfterSeconds: 30

  template:
    metadata:
      name: 'hello-cluster-{{clusterName}}'
    spec:
      source:
        repoURL: git@github.com:mednax-it/devops-aks-apps.git
        targetRevision: HEAD
        path: hello-cluster
        helm:
          values: |
            version: '0.0.21'
            environment: 'dev'
            url: 'example.com'
      destination:
        name: '{{clusterName}}'
        namespace: 'dev'
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
