apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-cluster
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: placement
        name: single-replica-placement 
        requeueAfterSeconds: 30

  template:
    metadata:
      name: 'hello-cluster-{{.clusterName}}'
    spec:
      source:
        repoURL: git@github.com:mednax-it/devops-aks-apps.git
        targetRevision: HEAD
        path: hello-cluster
        helm:
          parameters:
            - name: sha
              value: $ARGOCD_APP_REVISION
          values: |
            version: '0.0.21'
            environment: 'dev'
            url: 'example.com'
      destination:
        name: '{{.clusterName}}'
        namespace: '{{env}}'
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
