apiVersion: spv.no/v2beta1 
kind: AzureKeyVaultSecret
metadata:
  name: devops-test-key 
spec:
  vault:
    name: {{ (index .Values .Values.environment).keyvault_name }}
    object:
      name: DEVOPS-TEST-KEY             # name of the akv object
      type: secret                      # akv object type
